# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.2.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from loginhistory import Ui_Dialog
from accounts import Ui_Dialog2
from transactions import Ui_Dialog3


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(844, 619)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(
            QtCore.QRect(60, 130, 721, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.LoginSec = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.LoginSec.setContentsMargins(0, 0, 0, 0)
        self.LoginSec.setObjectName("LoginSec")
      #  self.HistoryBrowser = QtWidgets.QTextBrowser(     self.verticalLayoutWidget_2)
   #     self.HistoryBrowser.setObjectName("HistoryBrowser")

        self.HistoryBrowser = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.HistoryBrowser.setObjectName("WelcomeInfo")
        self.HistoryBrowser.setStyleSheet("background-color:#ffffff;")
        self.LoginSec.addWidget(self.HistoryBrowser)
        self.HistoryButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.HistoryButton.setObjectName("HistoryButton")
        self.HistoryButton.clicked.connect(self.view_history)
        self.LoginSec.addWidget(self.HistoryButton, 0,
                                QtCore.Qt.AlignmentFlag.AlignRight | QtCore.Qt.AlignmentFlag.AlignBottom)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(
            QtCore.QRect(60, 280, 721, 141))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.LoginSec = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_3)
        self.LoginSec.setContentsMargins(0, 0, 0, 0)
        self.LoginSec.setObjectName("LoginSec")
        #self.accountBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget_3)
        # self.accountBrowser.setObjectName("accountBrowser")
        self.accountBrowser = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.accountBrowser.setObjectName("WelcomeInfo")
        self.accountBrowser.setStyleSheet("background-color:#ffffff;")

        self.LoginSec.addWidget(self.accountBrowser)
        self.AccountButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.AccountButton.setObjectName("AccountButton")
        self.AccountButton.clicked.connect(self.view_accounts)

        self.LoginSec.addWidget(
            self.AccountButton, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(
            QtCore.QRect(60, 430, 721, 141))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.TransactionSec = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_4)
        self.TransactionSec.setContentsMargins(0, 0, 0, 0)
        self.TransactionSec.setObjectName("TransactionSec")
        # self.TransactionBrowser_2 = QtWidgets.QTextBrowser(self.verticalLayoutWidget_4)
        # self.TransactionBrowser_2.setObjectName("TransactionBrowser_2")

        self.TransactionBrowser_2 = QtWidgets.QLabel(
            self.verticalLayoutWidget_4)
        self.TransactionBrowser_2.setObjectName("TransactionBrowser_2")
        self.TransactionBrowser_2.setStyleSheet("background-color:#ffffff;")
        self.TransactionSec.addWidget(self.TransactionBrowser_2)

        self.TransactionButton = QtWidgets.QPushButton(
            self.verticalLayoutWidget_4)
        self.TransactionButton.setObjectName("TransactionButton")
        self.TransactionSec.addWidget(
            self.TransactionButton, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.TransactionButton.clicked.connect(self.view_transactions)

        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 20, 721, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.WelcomeSec = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.WelcomeSec.setContentsMargins(0, 0, 0, 0)
        self.WelcomeSec.setObjectName("WelcomeSec")
        # self.WelcomeInfo = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        # self.WelcomeInfo.setObjectName("WelcomeInfo")

        self.WelcomeInfo = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.WelcomeInfo.setObjectName("WelcomeInfo")
        self.WelcomeInfo.setStyleSheet("background-color:#ffffff;")

        self.WelcomeSec.addWidget(self.WelcomeInfo)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.HistoryButton, self.TransactionButton)
        MainWindow.setTabOrder(self.TransactionButton,
                               self.TransactionBrowser_2)
        MainWindow.setTabOrder(self.TransactionBrowser_2, self.WelcomeInfo)

    def retranslateUi(self, MainWindow):
        firstname = "[FIRST]"
        secondname = "[SECOND]"
        username = "[usrname]"

        trans = "Recent Transactions\n                TO                                AMOUNT\n" + \
            "4567-*****-*****               500 HKD" + \
                "1427-*****-*****             6782 HKD  "

        msg = firstname + " " + secondname + "\n" + "welcome, " + username + "\n"
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        self.HistoryBrowser.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                               "p, li { white-space: pre-wrap; }\n"
                                               "</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"

                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">Current Login Time:    10/10/2021  03:01:23 HKT<br /><br />Login History:  10/10/2021  03:01:23 HKT<br />                         10/10/2021  03:01:23 HKT<br />                         10/10/2021  03:01:23 HKT<br />                         06/10/2021  14:07:49 HKT</span></p></body></html>"))
        self.HistoryButton.setText(_translate(
            "MainWindow", "View Login History"))
        self.accountBrowser.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                               "p, li { white-space: pre-wrap; }\n"
                                               "</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">Account Balance:<br /><br />SAVINGS:    6000 HKD<br />CURRENT:    6770 HKD</span></p></body></html>"))
        self.AccountButton.setText(_translate(
            "MainWindow", "View All Accounts"))
        self.TransactionBrowser_2.setText(_translate("MainWindow", trans))
        self.TransactionButton.setText(_translate(
            "MainWindow", "View All Transactions"))
        # self.WelcomeInfo.setHtml(_translate("WelcomeInfo", "<p></p>"
        # "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#352e77;\">Welcome [username] to xyz bank</span></p></body></html>"))
        self.WelcomeInfo.setText(_translate(
            "WelcomeInfo", msg))

    def view_history(self):
        self.Dialog = QtWidgets.QWidget()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self.Dialog)
        self.Dialog.show()

    def view_accounts(self):
        self.Dialog = QtWidgets.QWidget()
        self.ui = Ui_Dialog2()
        self.ui.setupUi(self.Dialog)
        self.Dialog.show()

    def view_transactions(self):
        self.Dialog = QtWidgets.QWidget()
        self.ui = Ui_Dialog3()
        self.ui.setupUi(self.Dialog)
        self.Dialog.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
