# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import FaceRecognition.faces as faces
import FaceRecognition.face_capture as face_capture
from register_user import Ui_Dialog as register_user_gui


class UI_Form(object):

    def __init__(self):
        self.loginWithFaceIdButton = QtWidgets.QPushButton(Form)
        self.loginWithPasswordButton = QtWidgets.QPushButton(Form)
        self.existingUserLabel = QtWidgets.QLabel(Form)
        self.newUserLabel = QtWidgets.QLabel(Form)
        self.createAccountButton = QtWidgets.QPushButton(Form)
        self.welcomeLabel = QtWidgets.QLabel(Form)
        self.bankPicture = QtWidgets.QLabel(Form)
        self.return_dict = {}
        self.user_details = {}

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(684, 549)
        Form.setAutoFillBackground(False)

        self.loginWithFaceIdButton.setGeometry(QtCore.QRect(200, 430, 201, 61))
        self.loginWithFaceIdButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginWithFaceIdButton.setObjectName("loginWithFaceIdButton")
        self.loginWithFaceIdButton.clicked.connect(self.login_with_face_id)

        self.loginWithPasswordButton.setGeometry(QtCore.QRect(440, 430, 201, 61))
        self.loginWithPasswordButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginWithPasswordButton.setObjectName("loginWithPasswordButton")

        self.existingUserLabel.setGeometry(QtCore.QRect(50, 430, 131, 61))
        self.existingUserLabel.setObjectName("existingUserLabel")

        self.newUserLabel.setGeometry(QtCore.QRect(50, 360, 111, 71))
        self.newUserLabel.setObjectName("newUserLabel")

        self.createAccountButton.setGeometry(QtCore.QRect(200, 370, 441, 51))
        self.createAccountButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.createAccountButton.setObjectName("createAccountButton")
        self.createAccountButton.clicked.connect(self.create_new_user)

        self.welcomeLabel.setGeometry(QtCore.QRect(270, 200, 221, 31))
        self.welcomeLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.welcomeLabel.setObjectName("welcomeLabel")

        self.bankPicture.setGeometry(QtCore.QRect(220, 80, 231, 111))
        self.bankPicture.setText("")
        self.bankPicture.setPixmap(QtGui.QPixmap("../Images/bank6.png"))
        self.bankPicture.setScaledContents(True)
        self.bankPicture.setObjectName("bankPicture")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.loginWithFaceIdButton.setText(_translate("Form", "Login with faceID"))
        self.loginWithPasswordButton.setText(_translate("Form", "Login with Password"))
        self.existingUserLabel.setText(_translate("Form", "Existing User?"))
        self.newUserLabel.setText(_translate("Form", "New User?"))
        self.createAccountButton.setText(_translate("Form", "Create account"))
        self.welcomeLabel.setText(_translate("Form", "Welcome to Credit City"))

    def login_error_handler(self):
        error_widget = QtWidgets.QMessageBox()
        error_widget.setWindowTitle("Login Failed")
        error_widget.setIcon(QtWidgets.QMessageBox.Critical)
        error_widget.setText(self.return_dict['message'])

        run = error_widget.exec_()

    def login_with_face_id(self, Form):
        self.return_dict = faces.main()
        print(self.return_dict)
        if self.return_dict == {} or not self.return_dict['success']:
            self.login_error_handler()

    def create_new_user(self, Form):
        self.register_user_dialog = QtWidgets.QDialog()
        self.register_user_dialog.setWindowTitle("Register New User")
        self.register_user_dialog.setGeometry(500, 500, 500, 200)

        self.user_name_label = QtWidgets.QLabel(self.register_user_dialog)
        self.user_name_label.setText("Username")
        self.user_name_label.move(20, 20)
        self.user_name_input = QtWidgets.QLineEdit(self.register_user_dialog)
        self.user_name_input.move(100, 20)

        self.password_label = QtWidgets.QLabel(self.register_user_dialog)
        self.password_label.setText("Password")
        self.password_label.move(20, 60)
        self.password_input = QtWidgets.QLineEdit(self.register_user_dialog)
        self.password_input.move(100, 60)

        self.register_button = QtWidgets.QPushButton(self.register_user_dialog)
        self.register_button.setText("Register User")
        self.register_button.setGeometry(170, 150, 150, 50)
        self.register_button.clicked.connect(self.get_new_user_data)
        self.register_user_dialog.exec()
        self.return_dict = face_capture.main(self.user_details)

    def get_new_user_data(self):
        user_name = self.user_name_input.text()
        password = self.password_input.text()

        self.user_details = {'username': user_name,
                             'password': password
                             }
        self.register_user_dialog.close()


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = UI_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
